name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++-7, g++-9, clang++]
        build: [Debug, Release]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      # install dependencies
      - name: install dependencies (Mac)
        if: matrix.os == 'macos-latest'
        run: brew install boost
      - name: install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -yq libboost1.65-dev
      - name: checkout submodules
        shell: bash
        if: matrix.os != 'macos-latest' || matrix.compiler != 'g++-7'
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: ${{ matrix.build }} build
        env:
          CXX: ${{ matrix.compiler }}
          BUILDTYPE: ${{ matrix.build }}
        if: matrix.os != 'macos-latest' || matrix.compiler != 'g++-7'
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=$(echo $BUILDTYPE)
          make
          sudo make install

      - name: Set core dump
        if: matrix.os != 'macos-latest'
        run: |
          sudo mkdir -p /cores
          ulimit -c unlimited
          echo '/cores/core.%h.%e.%t' | sudo tee -a /proc/sys/kernel/core_pattern

      - name: ${{ matrix.build }} test
        if: matrix.os != 'macos-latest' || matrix.compiler != 'g++-7'
        run: |
          cd build
          ctest -V

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: core
          path: /cores
