name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++-7, g++-9, clang++]
        build: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: checkout submodules
        shell: bash
        if: matrix.os != 'macos-latest' || matrix.compiler != 'g++-7'
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: ${{ matrix.build }} build
        env:
          CXX: ${{ matrix.compiler }}
          BUILDTYPE: ${{ matrix.build }}
        if: matrix.os != 'macos-latest' || matrix.compiler != 'g++-7'
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=$(echo $BUILDTYPE)
          make
          sudo make install

      - name: ${{ matrix.build }} test
        if: matrix.os != 'macos-latest' || matrix.compiler != 'g++-7'
        run: |
          cd build
          ctest -V
